- type: gameMapPool
  id: DefaultMapPool
  maps:
  - Atlas
  - Bagel
  - Box
  - Cluster
  - Core
  - Fland
  - Marathon
  - Meta
  - Omega
  - Origin
  - Packed
  - Reach
  - Saltern
# DeltaV
  - Arena
  - Asterisk
  - Edge
  - Hammurabi
  - Pebble
  - Shoukou
  - Tortuga
  - TheHive
  #- Submarine
