using Content.Shared.Masonator;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.AutoGenerated;

namespace Content.Client.Masonator.UI;
[GenerateTypedNameReferences]
public sealed partial class AccountRow : PanelContainer
{
    public BankAccount acct;
    public AccountRow(BankAccount account)
    {
        RobustXamlLoader.Load(this);
        acct = account;
    }
}
