using Content.Shared.Masonator;
using Content.Client.Masonator;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.AutoGenerated;

namespace Content.Client.Masonator.UI;

[GenerateTypedNameReferences]
public sealed partial class BalanceRow : PanelContainer
{
    public AccountBalance? bal;
    public BalanceRow()
    {
        RobustXamlLoader.Load(this);
    }
}
